imports:
  - { resource: @LibrBundle/Resources/config/services.yml }

framework:
  charset:       UTF-8
  error_handler: null
  csrf_protection: { enabled: true, secret: xxxxxxxxxx }
  router:          { resource: "%kernel.root_dir%/config/routing.yml" }
  validation:      { enabled: true, annotations: true }
  templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
  translator:      { fallback: en }
  session:         { default_locale: pl, lifetime: 3600, auto_start: true, name: symfony }

# Twig Configuration
twig:
  debug:            %kernel.debug%
  strict_variables: %kernel.debug%

# Assetic Configuration
# assetic: ~

# Doctrine Configuration
doctrine:
 dbal:
   dbname:   library
   user:     library
   password: asdf
   logging:  %kernel.debug%
 orm:
   auto_generate_proxy_classes: %kernel.debug%
   mappings:
     LibrBundle: ~

# Base Application Configuration
sonata_base_application:
  entities:
    book:
      class: Application\LibrBundle\Admin\BookAdmin
      entity: Application\LibrBundle\Entity\Book
      controller: "LibrBundle:Admin"
      label: Książki
      group:  Encje
      list: 
        title: 
          identifier: true
        author:
