imports:
  - { resource: @LibrBundle/Resources/config/services.yml }

framework:
  charset:       UTF-8
  error_handler: null
  csrf_protection: { enabled: true, secret: xxxxxxxxxx }
  router:          { resource: "%kernel.root_dir%/config/routing.yml" }
  validation:      { enabled: true, annotations: true }
  templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
  translator:      { fallback: pl }
  session:         { default_locale: pl, lifetime: 3600, auto_start: true, name: symfony }

# Twig Configuration
twig:
  debug:            %kernel.debug%
  strict_variables: %kernel.debug%

# Assetic Configuration
# assetic: ~

# Doctrine Configuration
doctrine:
 dbal:
   dbname:   library
   user:     library
   password: asdf
   logging:  %kernel.debug%
 orm:
   auto_generate_proxy_classes: %kernel.debug%
   mappings:
     LibrBundle: ~

# Services
parameters:
  libr.admin.book.class: Application\LibrBundle\Entity\Book

services:
  libr.admin.book:
    class: Application\LibrBundle\Admin\BookAdmin
    arguments:
      - %libr.admin.book.class%
      - LibrBundle:Admin
    tags:
      sonata.admin:
        name: sonata.admin
        manager_type: orm
        group: Encje
        label: Książki

# Admin Configuration
sonata_admin:
  entities:
    book:
      class: Application\LibrBundle\Admin\BookAdmin
      entity: Application\LibrBundle\Entity\Book
      controller: "LibrBundle:Admin"
      label: Książki
      group:  Encje
      max_per_page: 5
      base_route_pattern: book
      list: 
        title: 
          identifier: true
        author:
        destination:
        createdAt:
      filter:
        title:
        author:
        destination:
          filter_field_widget: Sonata\AdminBundle\Filter\ChoiceFilter
          filter_field_options: 
            choices: {all: all, shelf: shelf, wishlist: wishlist}
      form:
        title:
        author:
        destination:
          form_field_widget: Symfony\Component\Form\ChoiceField
          form_field_options: 
            choices: {shelf: shelf, wishlist: wishlist}
      form_groups:
        "Important fields group":
          fields: [title]
        "Other less important fields":
          fields: [author, destination]
      form_options: {validation_groups: Default}
