Sonata:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
SonataPool:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    type: sonata_admin
Libr:
    resource: "@LibrBundle/Resources/config/routing.yml"
