Sonata:
    resource: "@SonataBaseApplicationBundle/Resources/config/routing/sonata_base_application.xml"
SonataPool:
    resource: "@SonataBaseApplicationBundle/Resources/config/routing/sonata_base_application.xml"
    type: sonata_base_application
Libr:
    resource: "@LibrBundle/Resources/config/routing.yml"
