<?php

namespace Application\LibrBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{
  public function getBooks($destination = "shelf")
  {
    return $this->_em->createQuery('SELECT b FROM Application\LibrBundle\Entity\Book b WHERE b.destination = :dest')
      ->setParameters(array("dest" => $destination))
      ->getResult();
  }
}
